name: Validate staging repository

on:
  push:
    branches: [staging]
  pull_request:
    branches: [main, staging]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - run: nix run .#build-public
